@echo off
echo 正在清理旧的构建文件...
del /f /s /q .\build
del /f /s /q .\dist
rmdir /s /q .\build
rmdir /s /q .\dist
echo 为减少打包后程序大小，将卸载所有已安装的包...
python -m pip freeze > uninstall_list.txt
python -m pip uninstall -r uninstall_list.txt -y
echo 清理临时卸载列表...
del /f /q uninstall_list.txt
echo 正在更新pip...
python -m pip install --upgrade pip
echo 正在安装PyInstaller...
python -m pip install PyInstaller
echo 正在重新安装所有依赖...
python -m pip install -r requirements.txt
echo 正在打包...
python -m PyInstaller .\build.spec --noconfirm
echo 打包完成！